[env]
_.file = ".env"
DATABASE_URL = "sveltekit_fyi.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)&_pragma=foreign_keys(ON)"
RUN_MIGRATIONS = "false"
LOG_LEVEL = "DEBUG"

[tasks.clean]
run = ["rm -rf ./bin", "rm -rf sveltekit-fyi-backup*.db"]

[tasks."dev:web"]
env = { NODE_ENV = "development", API_HOST = "http://localhost:8000" }
dir = "{{config_root}}/web"
run = "pnpm dev"

[tasks."dev:server"]
env = { APP_ENV = "development" }
run = "go run main.go"

[tasks.dev]
run = [{tasks = ["dev:web", "dev:server"]}]

[tasks.test]
run = "go test -v ./..."

[tasks."migrate:add"]
usage ='''arg "<task_name>"'''
run = "go tool goose -dir ./migrations create {{usage.task_name}} sql"

[tasks."migrate:up"]
run = "go tool goose -dir ./migrations sqlite3 $DATABASE_URL up"

[tasks."migrate:down"]
run = "go tool goose -dir ./migrations sqlite3 $DATABASE_URL down"

[tasks.lint]
run = "golangci-lint run --timeout 5m"

[tasks.build]
depends = ["clean"]
run = "go build -o ./bin/main main.go"

[tasks."build:web"]
dir = "{{config_root}}/web"
run = "pnpm build"

[tasks.preview]
env = { NODE_ENV = "production", API_HOST = "http://localhost:8000" }
dir = "{{config_root}}/web"
run = "pnpm preview"
